
options:
  long_puts:
  - SPY
  - QQQ
  - TWTR
  - GRPN
  - SHLD
  - AAPL
  - GOOG
  - AMZN
  - MSFT
  - FB
  - PCG
  covered_calls:
  - BRKB
  - PCG
  - SPY
  - QQQ
  - AAPL
  - AMZN
  - GOOG
  - MSFT
  - FB
  - PSEC
  long_calls:
  - PCG
  - AAPL
  - QQQ
  - SPY

